# Generated by Django 4.0.1 on 2022-02-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
